// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Data.EF.Models;

public partial class Color
{
    public int ColorId { get; set; }

    public string ColorName { get; set; }

    public string HexCode { get; set; }

    public string Image { get; set; }

    public virtual ICollection<Underwear> Underwears { get; set; } = new List<Underwear>();
}