// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Data.EF.Models;

public partial class Cut
{
    public int CutId { get; set; }

    public string CutType { get; set; }

    public string CutDescription { get; set; }

    public virtual ICollection<Underwear> Underwears { get; set; } = new List<Underwear>();
}