// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreFront.Data.EF.Models;

public partial class Underwear
{
    public int UnderwearId { get; set; }

    public int? CutId { get; set; }

    public int? BrandId { get; set; }

    public string CutType { get; set; }

    public int SmallQty { get; set; }

    public int MediumQty { get; set; }

    public int LargeQty { get; set; }

    public decimal Price { get; set; }

    public int? ColorId { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Color Color { get; set; }

    public virtual Cut Cut { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}